default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: my_restaurant_app_development
  username: aki
  password: password
  host: localhost
  port: 5433

test:
  <<: *default
  database: my_restaurant_app_test
  username: aki
  password: password
  host: localhost
  port: 5433

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
