default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: aki
  password: password
  host: localhost
  port: 5433

development:
  <<: *default
  database: my_restaurant_app_development

test:
  <<: *default
  database: my_restaurant_app_test

production:
  <<: *default
  database: my_restaurant_app_production
  username: my_restaurant_app
  password: <%= ENV["MY_RESTAURANT_APP_DATABASE_PASSWORD"] %>
